site_name: The Casper Show
theme:
  name: material

  icon:
    logo: fontawesome/solid/cat

  favicon: assets/wand-magic-sparkles-solid.svg

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: main_theme
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      accent: blue 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  
      primary: brown
      accent: blue
  font:
    code: Jetbrains Mono
    text: Poppins

  nav:
    - Welcome: 'index.md'
    - About Me: 'About Me.md'
    - Portfolio: 'Portfolio.md'
    - My Blog:
      - Casper Blog: 'Blog.md'
      - Computer Science:
      - Life:

extra_css:
  - stylesheets/extra.css

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SCWinter259
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/casper-nguyen-298302215/

# some extensions (allows us to do some highlighting of our code)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/SCWinter259"  target="_blank" rel="noopener">Casper Nguyen</a>